version: '3'
volumes:
  node_modules:
  postgres:

services:
  messenger:
    container_name: diabetes_messenger
    hostname: diabetes_messenger
    image: rabbitmq
    command: "rabbitmq-server"
    environment:
      - "RABBITMQ_DEFAULT_USER=diabetes"
      - "RABBITMQ_DEFAULT_PASS=diabetes"

  db:
    container_name: diabetes_db
    hostname: diabetes_db
    image: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - "POSTGRES_DB=diabetes"
      - "POSTGRES_USER=diabetes"
      - "POSTGRES_PASSWORD=diabetes"
    ports:
      - 54322:5432

  redis:
    image: redis
    container_name: diabetes_redis
    hostname: diabetes_redis

  primary:
    container_name: diabetes_primary
    hostname: diabetes-erp.local
    build:
      context: .
      dockerfile: Dockerfile
    image: diabetes
    env_file: .env
    command: >
      bash -c "
        sleep 5 &&
        pip install -r requirements.txt &&
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - .:/app
      - ./etc/emails/:/tmp/emails/
    ports:
      - 8000:8000

  worker:
    container_name: diabetes_worker
    hostname: diabetes_worker
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    command: >
      bash -c "
        sleep 5 &&
        pip install -r requirements.txt &&
        celery --app=diabetes:celery_app worker -n %h
      "
    volumes:
      - .:/app
      - ./etc/emails/:/tmp/emails/